"""财经术语库（C12 /learn 常青科普页数据源）。

承接「什么是市盈率 / 换手率怎么看 / 杯柄形态是什么」这类教育型长尾搜索；纯科普、零行情/零版权依赖，
合规安全（只解释概念，不对任何标的给买卖建议）。每条 → 一个 answer-first + FAQPage 的 /learn/{slug} 页。
"""
from __future__ import annotations

# slug 必须 ascii、唯一、稳定（进 URL）。definition 写成可被 AI 整段引用的自洽段落。
GLOSSARY: list[dict] = [
    {"slug": "pe-ratio", "term": "市盈率（PE）", "aliases": ["市盈率", "PE", "本益比"],
     "definition": "市盈率（PE）= 股价 ÷ 每股收益（EPS），衡量为公司每一元盈利支付的价格，常用来横向比较同行业公司的估值高低。一般分为静态市盈率（按上一年报盈利）、动态市盈率（按预测盈利）与滚动市盈率（TTM，按最近四个季度盈利）。市盈率高低需结合行业、成长性与盈利稳定性综合看，单看数值容易误判。",
     "related": ["eps", "pb-ratio", "valuation", "peg"]},
    {"slug": "pb-ratio", "term": "市净率（PB）", "aliases": ["市净率", "PB"],
     "definition": "市净率（PB）= 股价 ÷ 每股净资产，衡量股价相对账面净资产的倍数，常用于银行、地产等重资产行业的估值参考。PB 越低代表相对净资产越便宜，但低 PB 也可能反映市场对其资产质量或盈利能力的担忧。",
     "related": ["pe-ratio", "roe", "valuation"]},
    {"slug": "ps-ratio", "term": "市销率（PS）", "aliases": ["市销率", "PS"],
     "definition": "市销率（PS）= 总市值 ÷ 营业收入，衡量股价相对营收的倍数，常用于尚未盈利或盈利波动大的成长型、科技型公司估值，因为它们的市盈率可能为负或失真。",
     "related": ["pe-ratio", "valuation", "growth-stock"]},
    {"slug": "roe", "term": "净资产收益率（ROE）", "aliases": ["ROE", "净资产收益率"],
     "definition": "净资产收益率（ROE）= 净利润 ÷ 净资产，衡量公司用股东资本赚钱的效率，是巴菲特等长期投资者最看重的盈利质量指标之一。持续较高且稳定的 ROE 通常意味着较强的竞争优势；但需留意 ROE 是否靠高杠杆堆出来（可拆解为净利率 × 总资产周转率 × 权益乘数，即杜邦分析）。",
     "related": ["eps", "pb-ratio", "net-margin"]},
    {"slug": "eps", "term": "每股收益（EPS）", "aliases": ["EPS", "每股收益", "每股盈利"],
     "definition": "每股收益（EPS）= 归属母公司净利润 ÷ 总股本，代表每一股对应的盈利。EPS 的同比/环比增速、以及是否超出市场一致预期（即财报「超预期/不及预期」），往往是财报公布后股价反应的关键。",
     "related": ["pe-ratio", "roe", "earnings"]},
    {"slug": "dividend-yield", "term": "股息率", "aliases": ["股息率", "分红率"],
     "definition": "股息率 = 每股现金分红 ÷ 股价，衡量持股每年能拿到的现金回报比例，是红利、价值类投资关注的指标。股息率高需确认分红的可持续性（是否来自稳定经营现金流），单纯因股价大跌导致的高股息率未必健康。",
     "related": ["cash-flow", "blue-chip", "valuation"]},
    {"slug": "turnover-rate", "term": "换手率", "aliases": ["换手率"],
     "definition": "换手率 = 某段时间成交股数 ÷ 流通股本，反映股票交易的活跃度与筹码换手程度。换手率突然放大常伴随分歧加剧或资金进出，需结合价格与量能一起判断，单看换手率不能确定方向。",
     "related": ["volume", "amplitude", "fund-flow"]},
    {"slug": "volume", "term": "成交量", "aliases": ["成交量", "量能"],
     "definition": "成交量是一段时间内实际成交的股数或金额，是判断价格走势可信度的重要佐证。「量价齐升」常被视为趋势较健康的信号，「价涨量缩」则可能意味着上涨动能不足；量是价的先行与验证，但任何单一指标都不构成买卖依据。",
     "related": ["turnover-rate", "ma", "macd"]},
    {"slug": "amplitude", "term": "振幅", "aliases": ["振幅"],
     "definition": "振幅 =（当日最高价 − 当日最低价）÷ 昨日收盘价，衡量当天价格波动的剧烈程度。振幅大说明日内多空分歧大、波动风险高；振幅持续放大往往出现在关键位置或消息驱动时。",
     "related": ["volume", "turnover-rate"]},
    {"slug": "float-market-cap", "term": "流通市值", "aliases": ["流通市值"],
     "definition": "流通市值 = 流通股本 × 股价，代表市场上可自由交易部分的总价值，决定了拉动股价所需的资金量级。与之相对的是总市值（总股本 × 股价），二者差异主要来自限售股。",
     "related": ["total-market-cap", "restricted-shares"]},
    {"slug": "total-market-cap", "term": "总市值", "aliases": ["总市值"],
     "definition": "总市值 = 总股本 × 股价，代表公司在二级市场的整体估值规模，常用于划分大盘股/中盘股/小盘股以及指数权重。",
     "related": ["float-market-cap", "blue-chip"]},
    {"slug": "northbound-capital", "term": "北向资金", "aliases": ["北向资金", "陆股通", "外资"],
     "definition": "北向资金指通过沪股通、深股通从香港流入 A 股的境外资金，因常被视为「聪明钱」而受到关注。其净流入/流出规模与持仓变化是市场风险偏好的参考之一，但北向资金也包含量化与套利盘，不宜简单等同于长期看多看空。",
     "related": ["fund-flow", "blue-chip"]},
    {"slug": "fund-flow", "term": "资金流向（主力资金）", "aliases": ["资金流向", "主力资金", "主力净流入"],
     "definition": "资金流向通过成交单的买卖方向与大小单拆分，估算主力（大单）资金的净流入或净流出，用于观察筹码在不同资金间的转移。不同数据口径差异较大，主力资金为统计估算而非真实账户数据，只能作为参考维度之一。",
     "related": ["northbound-capital", "volume", "dragon-tiger"]},
    {"slug": "limit-up-down", "term": "涨停 / 跌停", "aliases": ["涨停", "跌停", "涨跌停"],
     "definition": "A 股主板个股单日涨跌幅限制一般为 ±10%（ST 股 ±5%，科创板/创业板 ±20%），触及上/下限即「涨停/跌停」。涨停板的封单强度、是否反复打开，常被用来观察资金情绪与分歧；但打板属于高风险交易，与本站任何研判无关。",
     "related": ["amplitude", "auction", "dragon-tiger"]},
    {"slug": "auction", "term": "集合竞价", "aliases": ["集合竞价"],
     "definition": "集合竞价是在连续竞价（盘中撮合）开始前，在一段时间内集中申报、按最大成交量原则一次性撮合形成开盘价的机制。A 股早盘 9:15–9:25 为开盘集合竞价，其量能与高开/低开幅度常被用来感知当日情绪。",
     "related": ["volume", "limit-up-down"]},
    {"slug": "dragon-tiger", "term": "龙虎榜", "aliases": ["龙虎榜"],
     "definition": "龙虎榜是交易所公布的当日异常波动（如大幅涨跌、换手居前）个股的买卖前五席位明细，用于提高交易透明度。市场常借龙虎榜观察游资、机构席位的动向，但席位行为多变，不能据此推断后续走势。",
     "related": ["fund-flow", "limit-up-down"]},
    {"slug": "restricted-shares", "term": "限售股解禁", "aliases": ["限售股解禁", "解禁"],
     "definition": "限售股解禁指原本受锁定期限制的股份（如首发原始股、定增股）到期可上市流通。解禁会增加潜在流通供给，规模较大的解禁常被关注其对股价的压力，但实际影响取决于股东减持意愿与市场承接力。",
     "related": ["float-market-cap", "placement"]},
    {"slug": "cup-handle", "term": "杯柄形态", "aliases": ["杯柄形态", "杯柄"],
     "definition": "杯柄形态（Cup with Handle）由欧奈尔提出，是一种常见的中长期突破形态：股价先走出 U 形「杯体」修复，再在杯口附近小幅回踩整理形成「杯柄」，随后放量突破杯口颈线。它描述的是趋势整理后的结构特征，仅为形态学概念，不构成任何买卖建议。",
     "related": ["ma", "volume", "trend"]},
    {"slug": "macd", "term": "MACD 指标", "aliases": ["MACD"],
     "definition": "MACD（指数平滑异同移动平均线）由快慢两条均线之差（DIF）与其平均（DEA）构成，并以柱状图表示二者差值，用于观察趋势与动量的变化。常见关注点包括金叉/死叉、零轴上下与顶背离/底背离；技术指标存在滞后与失效，仅作辅助参考。",
     "related": ["ma", "kdj", "rsi"]},
    {"slug": "kdj", "term": "KDJ 指标", "aliases": ["KDJ"],
     "definition": "KDJ（随机指标）基于一段周期内的最高价、最低价与收盘价计算 K、D、J 三线，对价格的短期超买超卖较为敏感，常用于震荡行情。其在单边趋势中容易钝化，需与趋势类指标配合，且不构成交易依据。",
     "related": ["macd", "rsi", "ma"]},
    {"slug": "rsi", "term": "RSI 相对强弱指标", "aliases": ["RSI", "相对强弱指标"],
     "definition": "RSI（相对强弱指标）通过一段周期内上涨与下跌幅度之比，衡量价格动量的强弱，取值 0–100，常以 70/30 作为超买/超卖的参考线。RSI 适合震荡市，趋势市中可能长期处于超买或超卖区，仅作辅助参考。",
     "related": ["kdj", "macd"]},
    {"slug": "ma", "term": "均线（MA）", "aliases": ["均线", "MA", "移动平均线"],
     "definition": "均线（移动平均线）是一段周期内收盘价的算术平均，用来平滑价格、识别趋势方向，常见有 5/10/20/60/250 日线。均线的多头排列、支撑压力、金叉死叉是常用观察点；均线属于趋势跟随、天然滞后，不构成买卖信号。",
     "related": ["macd", "cup-handle", "trend"]},
    {"slug": "long-short", "term": "多头 / 空头", "aliases": ["多头", "空头", "做多", "做空"],
     "definition": "多头指看涨并买入持有、预期上涨获利的一方；空头指看跌的一方（在可融券/有衍生品的市场可借券做空）。「偏多/偏空」是对方向倾向的中性描述，A 股个股不能直接裸卖空，相关概念多用于情绪与对冲讨论。",
     "related": ["bull-bear", "trend"]},
    {"slug": "bull-bear", "term": "牛市 / 熊市", "aliases": ["牛市", "熊市"],
     "definition": "牛市指市场整体持续上涨、风险偏好高涨的阶段；熊市指整体持续下跌、情绪低迷的阶段；二者之间为震荡市。牛熊是事后对趋势的归纳描述，实时判断牛熊拐点极其困难，需警惕「这次不一样」的线性外推。",
     "related": ["long-short", "trend", "cyclical-stock"]},
    {"slug": "blue-chip", "term": "蓝筹股", "aliases": ["蓝筹股", "蓝筹"],
     "definition": "蓝筹股通常指市值大、经营稳健、盈利与分红记录良好、行业地位领先的成熟公司股票，波动相对较低。蓝筹常作为机构配置与红利策略的底仓，但「大而稳」不等于无风险，仍受宏观与行业周期影响。",
     "related": ["white-horse", "dividend-yield", "value-stock"]},
    {"slug": "white-horse", "term": "白马股", "aliases": ["白马股", "白马"],
     "definition": "白马股指业绩长期优良、信息透明、品牌与护城河清晰、被市场广泛认可的绩优股，与题材驱动的「黑马股」相对。白马股确定性较高，但当估值被充分定价后，超额收益空间与「白马失蹄」的风险同样需要关注。",
     "related": ["blue-chip", "value-stock", "growth-stock"]},
    {"slug": "growth-stock", "term": "成长股", "aliases": ["成长股"],
     "definition": "成长股指营收与利润处于较快扩张期、市场给予较高估值以反映未来成长预期的公司股票，常见于科技、医药、新能源等赛道。成长股估值对成长兑现高度敏感，一旦增速不及预期，估值与盈利可能「戴维斯双杀」。",
     "related": ["value-stock", "ps-ratio", "peg"]},
    {"slug": "value-stock", "term": "价值股", "aliases": ["价值股"],
     "definition": "价值股指相对其内在价值（盈利、净资产、现金流）估值较低、通常分红较稳的成熟公司股票，与成长股相对。价值投资强调安全边际，但需区分「真便宜」与「价值陷阱」（便宜是因为基本面在恶化）。",
     "related": ["growth-stock", "pe-ratio", "dividend-yield"]},
    {"slug": "cyclical-stock", "term": "周期股", "aliases": ["周期股"],
     "definition": "周期股指业绩随宏观经济或商品价格周期大幅波动的行业股票，如有色、煤炭、化工、航运、券商等。周期股常出现「低市盈率买在高点、高市盈率买在低点」的反直觉特征，需结合景气位置而非单看 PE。",
     "related": ["bull-bear", "pe-ratio"]},
    {"slug": "concept-stock", "term": "概念股 / 题材股", "aliases": ["概念股", "题材股"],
     "definition": "概念股/题材股指因某一主题（政策、技术、事件）而被市场关注、短期资金集中炒作的股票，其上涨更多由情绪与预期驱动而非当期业绩。题材轮动快、波动大、证伪风险高，与基本面投资是两套逻辑。",
     "related": ["fund-flow", "dragon-tiger"]},
    {"slug": "buyback", "term": "股票回购", "aliases": ["回购", "股票回购"],
     "definition": "股票回购指上市公司用自有资金从二级市场买回自家股份，可用于注销（提升每股收益）或股权激励。回购通常被解读为管理层认为股价被低估、并向市场传递信心，但也需看回购规模、资金来源与是否真实注销。",
     "related": ["eps", "cash-flow", "placement"]},
    {"slug": "placement", "term": "增发 / 配股", "aliases": ["增发", "配股", "定增"],
     "definition": "增发（含定向增发）与配股都是上市公司再融资手段，会增加股本。定增面向特定对象、常带折价与锁定期；配股按比例向老股东低价配售。再融资摊薄每股权益，市场会关注募资投向是否能创造高于摊薄成本的回报。",
     "related": ["restricted-shares", "buyback", "eps"]},
    {"slug": "goodwill", "term": "商誉", "aliases": ["商誉"],
     "definition": "商誉是企业并购时支付对价超过被并购方可辨认净资产公允价值的差额，记在资产负债表的资产端。当被并购业务未达预期时需计提「商誉减值」，会一次性冲击利润，是高溢价并购公司的重要风险点。",
     "related": ["net-margin", "earnings"]},
    {"slug": "net-margin", "term": "毛利率 / 净利率", "aliases": ["毛利率", "净利率"],
     "definition": "毛利率 =（营收 − 营业成本）÷ 营收，反映产品本身的盈利空间与议价能力；净利率 = 净利润 ÷ 营收，反映扣除所有费用税金后的最终赚钱效率。二者的水平与趋势是判断公司盈利质量与护城河的核心。",
     "related": ["roe", "cash-flow", "goodwill"]},
    {"slug": "cash-flow", "term": "现金流", "aliases": ["现金流", "经营现金流", "自由现金流"],
     "definition": "现金流分经营、投资、筹资三类活动。经营性现金流净额是否健康、是否与净利润匹配（「有利润没现金」需警惕），以及扣除资本开支后的自由现金流，是衡量公司「真实赚钱能力」的关键，比账面利润更难粉饰。",
     "related": ["net-margin", "dividend-yield", "debt-ratio"]},
    {"slug": "debt-ratio", "term": "资产负债率", "aliases": ["资产负债率", "负债率"],
     "definition": "资产负债率 = 总负债 ÷ 总资产，衡量公司的财务杠杆与偿债压力。负债率高低需结合行业特性（如金融、地产天然偏高）与债务结构、利息覆盖倍数综合判断，过高的杠杆在景气下行期风险放大。",
     "related": ["cash-flow", "roe"]},
    {"slug": "valuation", "term": "估值", "aliases": ["估值", "估值方法"],
     "definition": "估值是判断一家公司值多少钱的过程，常用相对估值（PE、PB、PS、EV/EBITDA 等横向比较）与绝对估值（DCF 现金流折现）两类方法。估值高低本身不等于贵或便宜，需与成长性、盈利质量、行业与利率环境一起看。",
     "related": ["pe-ratio", "pb-ratio", "ps-ratio", "peg"]},
    {"slug": "peg", "term": "PEG 指标", "aliases": ["PEG"],
     "definition": "PEG = 市盈率（PE）÷ 盈利增速（%），由彼得·林奇推广，用于把估值与成长性结合：PEG 约等于 1 常被视为估值与成长相对匹配。PEG 对增速预测高度敏感，增速本身难测，故只能作为粗略参考。",
     "related": ["pe-ratio", "growth-stock", "valuation"]},
    {"slug": "earnings", "term": "财报 / 业绩预告", "aliases": ["财报", "业绩预告", "业绩快报"],
     "definition": "A 股公司按季披露财报（一季报、半年报、三季报、年报），并在正式财报前可能发布业绩预告/快报。财报中的营收、净利润同比增速、是否超出一致预期，以及现金流与毛利率变化，是基本面研判的核心证据。",
     "related": ["eps", "net-margin", "cash-flow"]},
    {"slug": "trend", "term": "趋势（技术面）", "aliases": ["趋势", "技术面"],
     "definition": "趋势指价格在一段时间内的总体方向，分上升、下降与横盘震荡，技术分析的核心理念是「趋势一旦形成易于延续」。常用均线、趋势线、高低点结构来识别趋势，但趋势会反转、技术信号会失效，任何工具都不构成买卖建议。",
     "related": ["ma", "macd", "cup-handle", "bull-bear"]},
]

BY_SLUG: dict[str, dict] = {t["slug"]: t for t in GLOSSARY}
